### ISSUE TITLE
Not checking 'is_admin' in 'else' conditions

### ISSUE THREAD

**Issue by alivtar** [mohsenFN/FN-manager#1]
I have found an issue in three of your functions in 'main.py' file.
In these three below functions,
('set_anti_link' & 'set_anti_sticker' & 'set_anti_forward') of 'main.py' file, you are not checking for 'is_admin' truth value in 'else' conditions.

**Comment by mohsenFN** [comment]
Yes i see. i appreciate that.
I'll fix them as soon as possible.
